version: '3.7'
services:
  REPONAME_DOCKER:
    build: .
    image: qmcgaw/REPONAME_DOCKER
    container_name: REPONAME_DOCKER
    ports:
      - 8000:8000/tcp
    environment:
      - TZ=America/Montreal
    secrets:
      - postgres_user
      - postgres_password
    restart: always

secrets:
  postgres_user:
    file: ./postgres_user
  postgres_password:
    file: ./postgres_password
